version: "3.7"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin-user
      - MONGO_INITDB_ROOT_PASSWORD=admin-password
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./scripts/mong∑o/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro